 version: 2
 executors:
  docker:
    - image: circleci/node:10
 jobs:
   build_image:
     executor: docker
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Build image docker
           command: docker build -t larnico\nodejs-api_team11:latest docker/api/
       - run:
           name: Archive image docker
           command: docker save -o sauv_image_docker.tar larnico\nodejs-api_team11
 workflows:
   version: 2
   build-master:
     jobs:
       - build_image:
           filters:
             branches:
               only: master